services:
  - type: web
    name: hrms-lite-api
    runtime: python
    buildCommand: |-
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      export PATH="$HOME/.cargo/bin:$PATH"
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT